version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=root
      - POSTGRES_PASSWORD=root
      - MYSQL_DATABASE=translog
    ports:
      - '3306:3306'